apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: pod-kill-experiment
  namespace: default
spec:
  schedule: "*/1 * * * *"
  type: PodChaos
  historyLimit: 5
  concurrencyPolicy: Forbid
  podChaos:
    action: pod-kill
    mode: one
    selector:
      labelSelectors:
        project: chaosmesh-microservice
    duration: "30s"
    gracePeriod: 0
