apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: kill-mongodb-experiment
  namespace: default
spec:
  schedule: "@yearly"
  type: PodChaos
  historyLimit: 5
  concurrencyPolicy: Forbid
  podChaos:
    action: pod-kill
    mode: all
    selector:
      labelSelectors:
        app: mongodb
    duration: "60s"
    gracePeriod: 0
