apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: container-kill-experiment
  namespace: default
spec:
  action: container-kill
  mode: one
  containerNames: ["api-gateway"]
  selector:
    labelSelectors:
      app: api-gateway
  duration: "60s"
  gracePeriod: 0
